// this is just exporting, so could be removed
export {
  getChannelsRequestQuery,
  getChannelsResponse,
  getChannelByIdRequestParams,
  getChannelByIdResponse,
  getEpisodesRequestQuery,
  getEpisodesResponse,
  getEpisodeByIdRequestParams,
  getEpisodeByIdResponse,
  getSeriesRequestQuery,
  getSeriesResponse,
  getSeriesByIdRequestParams,
  getSeriesByIdResponse,
  getTimetableRequestQuery,
  getTimetableResponse,
  getProgramsRequestQuery,
  getProgramsResponse,
  getProgramByIdRequestParams,
  getProgramByIdResponse,
  getRecommendedModulesRequestQuery,
  getRecommendedModulesRequestParams,
  getRecommendedModulesResponse,
  signInRequestBody,
  signInResponse,
  signUpRequestBody,
  signUpResponse,
  getUserResponse,
} from '@wsh-2025/schema/src/openapi/schema';
